version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-1:497217256558:task-definition/onboarding-yj-td:8"
        LoadBalancerInfo:
          ContainerName: "onboarding-backend-yj"
          ContainerPort: 3000