  version: 0.2

  env:
    git-credential-helper: yes

  phases:
    pre_build:
      commands:
        - echo Logging in to Amazon ECR...
#        ecr에 올리려고 토큰을 받아오는 과정
        - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    build:
      commands:
        - echo Build started on `date`
        - echo Building the Docker image...
        - echo `pwd`
        - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
#        - cd docker
#        - docker build -t onboarding-backend-yj .

#        - make build를 실행하면 Makefile을 실행
        - make build
    post_build:
      commands:
        - echo Build completed on `date`
        - echo Pushing the Docker image...
        - make push
#        - printf '[{"name":"onboarding-nginx","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/onboardingwy-nginx:latest > imagedefinitions.$ENV.json

  artifacts:
    files:
#      - docker/imagedefinitions.$ENV.json
      - aws/taskdef.$ENV.json
      - aws/appspec.$ENV.yaml
#      - S3에 업로드